name: Build Chrome Monitor APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean project
      run: ./gradlew clean
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: chrome-monitor-apk
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Chrome Monitor v1.0.${{ github.run_number }}
        body: |
          ## Chrome Monitor APK
          
          ### Instalación:
          1. Descarga el APK
          2. Activa "Fuentes desconocidas" en tu teléfono
          3. Instala el APK
          4. Configura todos los permisos necesarios
          
          ### Configuración requerida:
          - Cámara ✅
          - Almacenamiento ✅  
          - Estadísticas de uso ✅
          - Mostrar sobre otras apps ✅
          
          ### Uso:
          - La app funciona en segundo plano
          - Monitorea cuando Chrome está abierto
          - Captura fotos automáticamente
          - Envía fotos por email
          
          **Nota:** Recuerda configurar tu email en el código antes de compilar.
        files: app/build/outputs/apk/debug/app-debug.apk
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}